const Employee=[
    {
        id:"100",
        uname:"John",
        age:"30",
        desg:"Developer",
        salary:"35000"
    },
    {
        id:"101",
        uname:"Luke",
        age:"34",
        desg:"Tester",
        salary:"35000"
    },
    {
        id:"102",
        uname:"Amas",
        age:"33",
        desg:"Developer",
        salary:"45000"
    },
    {
        id:"103",
        uname:"jack",
        age:"37",
        desg:"Developer",
        salary:"25000"
    }
]
export default Employee